### ISSUE TITLE
[Feature request] Add compat with bewitchment and comforts

### ISSUE THREAD

**Issue by Kuggle01** [Giggitybyte/SleepWarp#5]
Bewitchment and comforts both add beds that can be used to sleep until night during the day, bewitchment having coffins and comforts having hammocs, but with this mod installed too they do nothing

**Comment by Giggitybyte** [comment]
I'll take a look at how each mod works when I get some free time and see what is needed for compatibility 👍

**Comment by EnderSpy29** [comment]
that would be awesome, because sleeping bags dont work and thats problem my only issue :D

**Comment by FibreTTP** [comment]
Is this compatibility feasible for the upcoming retrofit?

**Comment by Giggitybyte** [comment]
There will be a few changes in 2.0.0 which will hopefully decrease the amount of conflicts with other mods; sleeping bags from Comforts and any bed block from other mods which allow you to sleep at night to skip to the next day (like vanilla) should work as intended. 

However, compatibility with hammocks from Comforts and bed blocks from other mods which allow sleeping during the day may not be possible due to how I have things implemented now.
The system is entirely based on the current time of day with 0 - 12542 ticks considered day and 12543 - 24000 ticks considered night, and there's no way for me tell that a bed is *supposed* to be used during the day so any attempt to sleep using a bed block like a Comforts hammock will result in the player instantly waking up. 
More than likely I'll need to add in special cases for each mod, but I would like to try and devise a generic solution which will make any of these kind of beds from any mod 'just work'.

Regardless, any sort of full-fledged mod compatibility will come in a smaller update shortly after 2.0.0 is released.
